#!/bin/bash

#SBATCH -J RNN_loss_landscape
#SBATCH -p gpu 
#SBATCH -A r00639
#SBATCH -o %j_output.txt
#SBATCH -e %j_errors.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jctanner@iu.edu
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node 4
#SBATCH --time=4-00:00:00
#SBATCH --mem=64G
#SBATCH --cpus-per-task=5


#Load any modules that your program needs
module load python

#Run your program
srun python get_total_weights.py
